function [fitresult, gof] = lc_fit(bf_x, bf_y)
%CREATEFIT(BF_X,BF_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : bf_x
%      Y Output: bf_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Sep-2021 10:34:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( bf_x, bf_y );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Sensor Data', 'Best Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Voltage [V]', 'Interpreter', 'none' );
ylabel( 'Force [N]', 'Interpreter', 'none' );
grid on
set(gca, 'Fontsize', 12)


