function [fitresult, gof] = mean_bestfit(dur, dAdt_mean)
%CREATEFIT(DUR,DADT_MEAN)
%  Create a fit.
%
%  Data for 'slope_best fit' fit:
%      X Input : dur
%      Y Output: dAdt_mean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jan-2022 14:36:00


%% Fit: 'slope_best fit'.
[xData, yData] = prepareCurveData( dur, dAdt_mean );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [1.38014557584442e-09 0.00106469691189843 -0.158336254122971 -0.00145060687431953];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'slope_best fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'dAdt_mean vs. dur', 'slope_best fit', 'Location', 'NorthEast' );
% % Label axes
% xlabel dur
% ylabel dAdt_mean
% grid on


